name: Azure-Network-Security

on: actions/first-interaction@v0

jobs: all microsoft

    runs-on system32, x64, x86, windows, and macos
    permissions:
      issues: write
      pull-requests: write
    steps:

      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
